language: node_js
sudo: false
node_js:
  - 0.12
cache:
  directories:
    - $(npm root -g)
branches:
  only:
    - master
    - dev
    - stage
    - testing
env:
  global:
    #JSPM_GITHUB_AUTH_TOKEN=[secured]
    - secure: IzfJEvFKDzR5lbRSo6lxFSv5q/99WTYlQTC4bMWYZRFNK1rkfsdd/qhSAUCUT+hkyapf1bp1aER9Z79Yi8ivtQpQRmSuiZ+yb+15YP1jCYuVjPFnthVOOrgsxJyjspYxgE5FzATra7KwlrkGL57kIeEqj1aR03qKT4vGd4IVygUa+9FEjEEhztgeJXaMX4/GOjui1yYhXm464/LaQNcUpiNE3h3KDPIvFX6Wvfvwmccu3JILXWAR46/t69tWhs36b5p/MpdoDlXceF6ZCbRWX35P8eqXUPoi84zimjgoCnpvVwaAEUiu+3N+EqwrSGVbQWjFxHBqz2i2BNCT6xfPmU7ijie5bpdAjOdtz/9TKmjZk+nup/rd7wgvIAAuUYnFRUYGmuAjJf/D/kCb4SKmF86JzSaSmWqy+E8EoZSd2tpl041l0cStOhws8LEKRHZPzXHJhnqWrfNw94qbwnk83hPim382TmG37bED9v+HUFDA7IaAREKgmXNwJyU5sEdCFPhlNmgX1TrAi2dw0IeGNtez2IeQ+R+AYg2D/cZW44lIjFGSKyufNnByd4Tzu6ONgFof68hspGlJpMhe8Hw4qP7b6rvy2iI9atB7mSVPTf/kUSmWfRP/y30Rak0x2TAy+fu7tpfyxAZPgG4D8N0VvL69cDQ4kM9+oDaqQcqsjJg=
    #CODACY_PROJECT_TOKEN =[secured]
    - secure: DVIQY/YPaBR2qj9+xenQiJvFo0REwq0IatNGwHZ3CuYQYb/e9c931P4WKqp1rlnYSGJrhwejWxXfLcXDpSvQ8ba4CElWKmdS1dgUtFlm5b6Ct4r51UmGwuqGeC75/bUi5Q7qDMIyjEvn/wjNfF1s1re8Pzp2+Sy0VKD8ymEWO+HaQjxl59P37OJyByFeFx3krKyZA6kgGhXMg/NgS0ODtHFtR+NUrTCxXC5TanIaIGipzrSkfEPselNIqd+q92sCKwh6VPOeamLyUXxtZN6l6f1vnrhfEj62yHSDsDSNp03cR38HL809a1nmMD8pOiGz3cKCGOB85EBJ0Tq2kkicp3DGYB8AfVCZqbResI4+T/xSndXBA19lVRZ9RnmnZDOmpCDFT0uXur251O5L1eytVgVUZLnVf0nPlMerqdwDszoQtfwE+nT26QGaR+yjb1MIRyXlDGp/lBo73qv4XlCmGGUU52m5aBD98dEQGfkX07dETNCw+7b8dRnl4AEsqQSEh7HADXp227reCFQLwrKkJ0dF54V6L9w0hr7bsdUiaWaEyyQ2efjPzIMdJTeDwei0eOC2yKw5qmCT96UayDPcqEPG3QOd0gOMBQUSD79RcdOylYgalOwnDo6lsvWBDfAtI9Sz5aAvGDx+G6ZMy7EO7LHInvXHqGhcXgKVy650cg0=
before_install:
  - npm install -g deepify
  - npm install -g jspm
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - npm install -g babel@5.8.19
  - npm install -g browserify@11.2.0
  - npm install -g jscs@2.1.1
  - npm install -g mocha@2.3.3
  - npm install -g mocha-babel@3.0.0
  - npm install -g codacy-coverage@1.1.3
  - npm install -g chai@3.3.0
  - npm install -g jasmine-core@2.3.4
  - npm install -g istanbul@0.3.21
  - npm install -g istanbul-combine@0.3.0
  - npm install -g phantomjs@1.9.18
  - npm install -g karma@0.13.11
  - npm install -g karma-jspm@2.0.1
  - npm install -g karma-jasmine@0.3.6
  - npm install -g karma-babel-preprocessor@5.2.2
  - npm install -g karma-coverage@douglasduteil/karma-coverage#next
  - npm install -g karma-verbose-reporter@0.0.3
  - npm install -g karma-phantomjs-launcher@0.2.1
  - npm install -g karma-ng-html2js-preprocessor@0.2.0
  - cp test/package.json .
after_success:
  - npm run coverage
